name: Image Release Build

on:
  push:
    branches:
      - pr/test-docker-images-legacy
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  build-and-push:
    environment: release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./Dockerfile
          - name: operator
            dockerfile: ./cilium-operator.Dockerfile
          - name: operator-aws
            dockerfile: ./cilium-operator-aws.Dockerfile
          - name: operator-azure
            dockerfile: ./cilium-operator-azure.Dockerfile
          - name: operator-generic
            dockerfile: ./cilium-operator-generic.Dockerfile
          - name: hubble-relay
            dockerfile: ./hubble-relay.Dockerfile
          - name: clustermesh-apiserver
            dockerfile: ./clustermesh-apiserver.Dockerfile
          - name: docker-plugin
            dockerfile: ./cilium-docker-plugin.Dockerfile
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF##*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout Stable Branch Source Code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_RELEASE_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_RELEASE_PASSWORD }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Release Build ${{ matrix.name }}
        uses: docker/build-push-action@v2
        id: docker_build_release
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ github.sha }}
      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "docker.io/${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}@${{ steps.docker_build_release.outputs.digest }}" > image-digest/${{ matrix.name }}.txt
          echo "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}@${{ steps.docker_build_release.outputs.digest }}" >> image-digest/${{ matrix.name }}.txt
          echo "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ github.sha }}@${{ steps.docker_build_release.outputs.digest }}" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@v2
        with:
          name: image-digest ${{ matrix.name }}
          path: image-digest
          retention-days: 1
  image-digests:
    name: Display Digests
    runs-on: ubuntu-20.04
    needs: build-and-push
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/
      - name: Download digests of all images built
        uses: actions/download-artifact@v2
        with:
          path: image-digest/

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f -exec cat {} \;
